name: "C++ Format Checker"

on:
  pull_request:
    branches: [ main ]

jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dev packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libstdc++-*-dev

      - uses: cpp-linter/cpp-linter-action@v2.9.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 14
          lines-changed-only: true
          file-annotations: false
          step-summary: true
          format-review: true
          tidy-checks: '-*'
          ignore: 'subprojects'

      - name: Fail on format violations
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: |
          echo "This PR failed to pass the C++ source file format checks."
          exit 1
